# Generated by Django 5.1.4 on 2026-08-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_product_min_stock_product_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
