# Generated by Django 5.1.4 on 2026-08-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_amount_paid_alter_invoice_status_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='My Business', max_length=255)),
                ('business_address', models.TextField(default='123 Business St, City, Country')),
                ('phone_number', models.CharField(default='+1234567890', max_length=20)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=10)),
                ('invoice_footer', models.TextField(default='Thank you for your business.')),
                ('default_tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('currency', models.CharField(default='$', max_length=10)),
            ],
        ),
    ]
