# Generated by Django 5.1.4 on 2026-08-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_businesssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reference',
            field=models.CharField(blank=True, help_text='Optional reference number/note', max_length=50, null=True),
        ),
    ]
